package yankee.logic.ENUM;

public enum GermanyStatesEnum {
   BADENWURTTENMERG,
   BAVARIA,
   BERLIN,
   BRANDENBURG,
   BREMEN,
   HAMBURG,
   HESSE,
   LOWERSAXONY,
   MECKLENBURGVORPOMMERN,
   NORTHRHINEWESTPHALIA,
   RHINELANDPALATINATE,
   SAARLAND,
   SAXONY,
   SAXONYANHALT,
   SCHLESWIGHOLSTEIN,
   THURINGIA;   
}
